# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
#  - repo: "https://github.com/pre-commit/pre-commit-hooks"
#    rev: "v4.5.0"
#    hooks:
#      - id: "end-of-file-fixer"
#      - id: "check-merge-conflict"

  - repo: local
    hooks:
      - id: checkstyle
        name: Checkstyle (staged Java files)
        language: script
        entry: ./tools/checkstyle.sh
        types: [ java ]         # pre-commit passes only .java files
        pass_filenames: true  # so "$@" contains the files
