name: Pre-commit Checks

on:
  push:
    branches:
      - "master"
      - "*+precommit"
      - "*-rc"
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - "**"

# Declare default permissions as read only.
permissions: read-all

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'   # Or 'zulu', 'adopt', etc., if you prefer
          java-version: '8'

      - name: Build and test with Maven
        run: mvn -B clean verify

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit hooks
        run: pre-commit run
